#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPOSITORY_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_PATH="${REPOSITORY_ROOT}/install.yaml"
TEMP_PATH="$(mktemp "${TMPDIR:-/tmp}/cased-cd-install.XXXXXX")"

cleanup() {
  rm -f "${TEMP_PATH}"
}

trap cleanup EXIT

if ! command -v helm >/dev/null 2>&1; then
  echo "helm is required to generate install.yaml" >&2
  exit 1
fi

{
  echo "# Generated by scripts/generate-install-manifest.sh; do not edit manually."
  echo "# Regenerate with: npm run generate:install"
  helm template cased-cd "${REPOSITORY_ROOT}/chart" --namespace argocd
} > "${TEMP_PATH}"

mv "${TEMP_PATH}" "${OUTPUT_PATH}"
trap - EXIT

echo "Generated ${OUTPUT_PATH}"
